repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "npx eslint --fix src"
        language: system
  - repo: local
    hooks:
        - id: prettier
          name: prettier
          entry: bash -c "npx prettier src --write"
          language: system
